import 'package:flutter/widgets.dart';

class AppIcon {
  AppIcon._();

  static const kFontFam = 'AppIcon';
  static const String? kFontPkg = null;

  static const IconData abtesting =
      IconData(0xe800, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData activity =
      IconData(0xe801, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData additem =
      IconData(0xe802, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData additemalt =
      IconData(0xe803, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData addnote =
      IconData(0xe804, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData addtocart =
      IconData(0xe805, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData addtolist =
      IconData(0xe806, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData agile =
      IconData(0xe807, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData airplay =
      IconData(0xe808, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData airpods =
      IconData(0xe809, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData airpodsalt =
      IconData(0xe80a, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData alignbottom =
      IconData(0xe80b, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData alignh =
      IconData(0xe80c, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData alignleft =
      IconData(0xe80d, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData alignright =
      IconData(0xe80e, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData aligntop =
      IconData(0xe80f, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData alignv =
      IconData(0xe810, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData android =
      IconData(0xe811, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData apple =
      IconData(0xe812, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData applewatch =
      IconData(0xe813, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData applewatchsmile =
      IconData(0xe814, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData applewatchtime =
      IconData(0xe815, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData archive =
      IconData(0xe816, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData arrowbottomleft =
      IconData(0xe817, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData arrowbottomright =
      IconData(0xe818, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData arrowcircledown =
      IconData(0xe819, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData arrowcircleleft =
      IconData(0xe81a, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData arrowcircleright =
      IconData(0xe81b, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData arrowcircleup =
      IconData(0xe81c, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData arrowdown =
      IconData(0xe81d, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData arrowleft =
      IconData(0xe81e, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData arrowright =
      IconData(0xe81f, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData arrowsquaredown =
      IconData(0xe820, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData arrowsquareleft =
      IconData(0xe821, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData arrowsquareright =
      IconData(0xe822, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData arrowsquareup =
      IconData(0xe823, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData arrowtopleft =
      IconData(0xe824, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData arrowtopright =
      IconData(0xe825, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData arrowtotop =
      IconData(0xe826, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData arrowup =
      IconData(0xe827, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData artboard =
      IconData(0xe828, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData at =
      IconData(0xe829, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData attachdocument =
      IconData(0xe82a, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData back =
      IconData(0xe82b, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData backlog =
      IconData(0xe82c, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData barcode =
      IconData(0xe82d, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData barcodescan =
      IconData(0xe82e, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData batteryfull =
      IconData(0xe82f, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData batterylow =
      IconData(0xe830, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData batterymid =
      IconData(0xe831, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData batteryv =
      IconData(0xe832, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData bell =
      IconData(0xe833, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData bellalt =
      IconData(0xe834, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData bellaltring =
      IconData(0xe835, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData bellslash =
      IconData(0xe836, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData bellsnooze =
      IconData(0xe837, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData bid =
      IconData(0xe838, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData bill =
      IconData(0xe839, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData bitcoinsign =
      IconData(0xe83a, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData block =
      IconData(0xe83b, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData bold =
      IconData(0xe83c, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData bolt =
      IconData(0xe83d, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData book =
      IconData(0xe83e, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData bookalt =
      IconData(0xe83f, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData bookmark =
      IconData(0xe840, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData bottombar =
      IconData(0xe841, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData briefcase =
      IconData(0xe842, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData broadcast =
      IconData(0xe843, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData brush =
      IconData(0xe844, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData bullhorn =
      IconData(0xe845, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData cablehdmi =
      IconData(0xe846, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData cablejack =
      IconData(0xe847, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData cablelan =
      IconData(0xe848, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData cablelightning =
      IconData(0xe849, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData cablemagsafe =
      IconData(0xe84a, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData cableusb =
      IconData(0xe84b, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData calendar =
      IconData(0xe84c, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData calendarday =
      IconData(0xe84d, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData calendarmonth =
      IconData(0xe84e, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData calendarnever =
      IconData(0xe84f, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData calendarweek =
      IconData(0xe850, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData callin =
      IconData(0xe851, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData callout =
      IconData(0xe852, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData camera =
      IconData(0xe853, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData cameraalt =
      IconData(0xe854, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData cameraalt2 =
      IconData(0xe855, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData cardboardvr =
      IconData(0xe856, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData cast =
      IconData(0xe857, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData cellborderbottom =
      IconData(0xe858, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData cellborderfull =
      IconData(0xe859, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData cellborderleft =
      IconData(0xe85a, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData cellborderright =
      IconData(0xe85b, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData cellbordertop =
      IconData(0xe85c, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData cellempty =
      IconData(0xe85d, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData cellfull =
      IconData(0xe85e, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData cellsplit =
      IconData(0xe85f, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData cellsplith =
      IconData(0xe860, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData cellsplitv =
      IconData(0xe861, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData chat =
      IconData(0xe862, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData checkmark =
      IconData(0xe863, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData checkmarkcircle =
      IconData(0xe864, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData checkmarksquare =
      IconData(0xe865, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData chevrondoubledown =
      IconData(0xe866, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData chevrondoubleleft =
      IconData(0xe867, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData chevrondoubleright =
      IconData(0xe868, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData chevrondoubleup =
      IconData(0xe869, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData chevrondown =
      IconData(0xe86a, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData chevronleft =
      IconData(0xe86b, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData chevronright =
      IconData(0xe86c, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData chevronup =
      IconData(0xe86d, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData clipboard =
      IconData(0xe86e, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData clock =
      IconData(0xe86f, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData close =
      IconData(0xe870, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData closecircle =
      IconData(0xe871, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData closesquare =
      IconData(0xe872, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData cloud =
      IconData(0xe873, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData clouddownload =
      IconData(0xe874, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData cloudminus =
      IconData(0xe875, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData cloudplus =
      IconData(0xe876, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData cloudupload =
      IconData(0xe877, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData cloudyday =
      IconData(0xe878, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData cloudynight =
      IconData(0xe879, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData code =
      IconData(0xe87a, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData cog =
      IconData(0xe87b, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData coin =
      IconData(0xe87c, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData collapse =
      IconData(0xe87d, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData collapse2 =
      IconData(0xe87e, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData collapsealt =
      IconData(0xe87f, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData collapsealt2 =
      IconData(0xe880, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData collapsedown =
      IconData(0xe881, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData collapseleft =
      IconData(0xe882, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData collapseright =
      IconData(0xe883, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData collapseup =
      IconData(0xe884, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData collapsewide =
      IconData(0xe885, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData command =
      IconData(0xe886, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData comment =
      IconData(0xe887, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData compass =
      IconData(0xe888, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData contentleft =
      IconData(0xe889, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData contentright =
      IconData(0xe88a, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData continueicon =
      IconData(0xe88b, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData controller =
      IconData(0xe88c, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData controlleralt =
      IconData(0xe88d, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData copy =
      IconData(0xe88e, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData copyalt =
      IconData(0xe88f, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData creditcard =
      IconData(0xe890, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData crop =
      IconData(0xe891, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData cursor =
      IconData(0xe892, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData cursorsquare =
      IconData(0xe893, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData cut =
      IconData(0xe894, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData cutalt =
      IconData(0xe895, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData database =
      IconData(0xe896, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData delete =
      IconData(0xe897, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData deploy =
      IconData(0xe898, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData designstudio =
      IconData(0xe899, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData designvalidation =
      IconData(0xe89a, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData desktop =
      IconData(0xe89b, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData desktop1 =
      IconData(0xe89c, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData desktop2 =
      IconData(0xe89d, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData desktop3 =
      IconData(0xe89e, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData devices =
      IconData(0xe89f, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData diamond =
      IconData(0xe8a0, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData disk =
      IconData(0xe8a1, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData distributeh =
      IconData(0xe8a2, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData distributev =
      IconData(0xe8a3, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData document =
      IconData(0xe8a4, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData dollarsign =
      IconData(0xe8a5, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData doubletap =
      IconData(0xe8a6, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData doubletaptwo =
      IconData(0xe8a7, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData download =
      IconData(0xe8a8, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData draftingcompass =
      IconData(0xe8a9, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData drag =
      IconData(0xe8aa, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData drawtextfield =
      IconData(0xe8ab, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData duplicate =
      IconData(0xe8ac, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData duplicatealt =
      IconData(0xe8ad, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData earth =
      IconData(0xe8ae, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData earthalt =
      IconData(0xe8af, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData editcircle =
      IconData(0xe8b0, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData editpencil =
      IconData(0xe8b1, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData editsquare =
      IconData(0xe8b2, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData editsquarefeather =
      IconData(0xe8b3, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData eraser =
      IconData(0xe8b4, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData eurosign =
      IconData(0xe8b5, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData exclamationmark =
      IconData(0xe8b6, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData exclamationtriangle =
      IconData(0xe8b7, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData exclude =
      IconData(0xe8b8, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData expand =
      IconData(0xe8b9, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData expand2 =
      IconData(0xe8ba, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData expandalt =
      IconData(0xe8bb, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData expandalt2 =
      IconData(0xe8bc, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData expanddown =
      IconData(0xe8bd, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData expandh =
      IconData(0xe8be, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData expandleft =
      IconData(0xe8bf, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData expandright =
      IconData(0xe8c0, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData expandup =
      IconData(0xe8c1, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData expandv =
      IconData(0xe8c2, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData expandwide =
      IconData(0xe8c3, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData exporticon =
      IconData(0xe8c4, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData eye =
      IconData(0xe8c5, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData eyedropper =
      IconData(0xe8c6, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData eyeslash =
      IconData(0xe8c7, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData faceid =
      IconData(0xe8c8, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData filearchive =
      IconData(0xe8c9, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData fileaudio =
      IconData(0xe8ca, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData filecloud =
      IconData(0xe8cb, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData filedownload =
      IconData(0xe8cc, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData fileempty =
      IconData(0xe8cd, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData fileexport =
      IconData(0xe8ce, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData filefont =
      IconData(0xe8cf, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData filegraphic =
      IconData(0xe8d0, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData fileimage =
      IconData(0xe8d1, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData fileimport =
      IconData(0xe8d2, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData filepdf =
      IconData(0xe8d3, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData filesearch =
      IconData(0xe8d4, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData filesketch =
      IconData(0xe8d5, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData filetable =
      IconData(0xe8d6, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData fileupload =
      IconData(0xe8d7, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData filevector =
      IconData(0xe8d8, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData filevideo =
      IconData(0xe8d9, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData film =
      IconData(0xe8da, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData filmalt =
      IconData(0xe8db, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData filmplay =
      IconData(0xe8dc, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData filter =
      IconData(0xe8dd, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData filteralt =
      IconData(0xe8de, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData flag =
      IconData(0xe8df, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData flatten =
      IconData(0xe8e0, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData flickleft =
      IconData(0xe8e1, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData flicklefttwo =
      IconData(0xe8e2, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData flickright =
      IconData(0xe8e3, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData flickrighttwo =
      IconData(0xe8e4, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData flipleft =
      IconData(0xe8e5, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData flipleftalt =
      IconData(0xe8e6, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData flipright =
      IconData(0xe8e7, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData fliprightalt =
      IconData(0xe8e8, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData floppy =
      IconData(0xe8e9, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData folder =
      IconData(0xe8ea, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData folderdelete =
      IconData(0xe8eb, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData folderminus =
      IconData(0xe8ec, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData folderopen =
      IconData(0xe8ed, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData folderplus =
      IconData(0xe8ee, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData font =
      IconData(0xe8ef, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData fontheight =
      IconData(0xe8f0, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData fontsize =
      IconData(0xe8f1, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData fontwidth =
      IconData(0xe8f2, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData gameboy =
      IconData(0xe8f3, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData gitbranch =
      IconData(0xe8f4, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData gitcommit =
      IconData(0xe8f5, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData gitfork =
      IconData(0xe8f6, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData gitmerge =
      IconData(0xe8f7, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData gitpull =
      IconData(0xe8f8, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData grid =
      IconData(0xe8f9, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData group =
      IconData(0xe8fa, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData halfh =
      IconData(0xe8fb, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData halfv =
      IconData(0xe8fc, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData hamburgermenu =
      IconData(0xe8fd, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData hammer =
      IconData(0xe8fe, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData harddrive =
      IconData(0xe8ff, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData heading =
      IconData(0xe900, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData headphone =
      IconData(0xe901, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData heart =
      IconData(0xe902, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData heavyrain =
      IconData(0xe903, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData heavyrainday =
      IconData(0xe904, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData heavyrainnight =
      IconData(0xe905, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData heavywind =
      IconData(0xe906, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData height =
      IconData(0xe907, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData history =
      IconData(0xe908, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData home =
      IconData(0xe909, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData horns =
      IconData(0xe90a, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData imac =
      IconData(0xe90b, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData image =
      IconData(0xe90c, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData imagecircle =
      IconData(0xe90d, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData imagegallery =
      IconData(0xe90e, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData imagewide =
      IconData(0xe90f, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData importicon =
      IconData(0xe910, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData indentleft =
      IconData(0xe911, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData indentleftalt =
      IconData(0xe912, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData indentright =
      IconData(0xe913, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData indentrightalt =
      IconData(0xe914, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData infocircle =
      IconData(0xe915, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData informationarchitecture =
      IconData(0xe916, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData intersect =
      IconData(0xe917, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData interview =
      IconData(0xe918, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData ios =
      IconData(0xe919, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData ipad =
      IconData(0xe91a, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData ipadh =
      IconData(0xe91b, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData iphone =
      IconData(0xe91c, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData iphoneh =
      IconData(0xe91d, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData iphonex =
      IconData(0xe91e, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData iphonexh =
      IconData(0xe91f, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData italic =
      IconData(0xe920, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData kanbanboard =
      IconData(0xe921, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData keyboard =
      IconData(0xe922, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData lan =
      IconData(0xe923, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData lanconnection =
      IconData(0xe924, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData lanerror =
      IconData(0xe925, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData laptop =
      IconData(0xe926, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData laugh =
      IconData(0xe927, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData layerstack =
      IconData(0xe928, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData layout1 =
      IconData(0xe929, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData layout2 =
      IconData(0xe92a, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData layout3 =
      IconData(0xe92b, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData layout4 =
      IconData(0xe92c, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData layout5 =
      IconData(0xe92d, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData leftbar =
      IconData(0xe92e, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData legoseriousplay =
      IconData(0xe92f, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData lifebelt =
      IconData(0xe930, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData linechart =
      IconData(0xe931, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData link =
      IconData(0xe932, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData lirasign =
      IconData(0xe933, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData listbullet =
      IconData(0xe934, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData listnumber =
      IconData(0xe935, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData lock =
      IconData(0xe936, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData lockalt =
      IconData(0xe937, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData loop =
      IconData(0xe938, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData macbookpro =
      IconData(0xe939, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData macpro =
      IconData(0xe93a, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData magicwand =
      IconData(0xe93b, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData mail =
      IconData(0xe93c, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData mapmarker =
      IconData(0xe93d, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData margin =
      IconData(0xe93e, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData marker =
      IconData(0xe93f, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData memorycard =
      IconData(0xe940, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData microphone =
      IconData(0xe941, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData microphonemute =
      IconData(0xe942, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData mildrain =
      IconData(0xe943, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData mildrainday =
      IconData(0xe944, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData mildrainnight =
      IconData(0xe945, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData minus =
      IconData(0xe946, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData minuscircle =
      IconData(0xe947, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData minussquare =
      IconData(0xe948, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData moneybill =
      IconData(0xe949, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData moneystack =
      IconData(0xe94a, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData moon =
      IconData(0xe94b, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData moreh =
      IconData(0xe94c, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData morev =
      IconData(0xe94d, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData mouse =
      IconData(0xe94e, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData mylocation =
      IconData(0xe94f, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData neutral =
      IconData(0xe950, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData next =
      IconData(0xe951, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData nextalt =
      IconData(0xe952, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData note =
      IconData(0xe953, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData notebook =
      IconData(0xe954, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData osx =
      IconData(0xe955, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData outdentleft =
      IconData(0xe956, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData outdentright =
      IconData(0xe957, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData package =
      IconData(0xe958, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData paintbucket =
      IconData(0xe959, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData paintroller =
      IconData(0xe95a, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData palette =
      IconData(0xe95b, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData panoramah =
      IconData(0xe95c, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData paperclip =
      IconData(0xe95d, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData paperprototype =
      IconData(0xe95e, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData paragraph =
      IconData(0xe95f, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData password =
      IconData(0xe960, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData paste =
      IconData(0xe961, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData pastealt =
      IconData(0xe962, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData pause =
      IconData(0xe963, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData pausealt =
      IconData(0xe964, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData pen =
      IconData(0xe965, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData pencil =
      IconData(0xe966, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData pencilcircle =
      IconData(0xe967, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData pencircle =
      IconData(0xe968, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData persona =
      IconData(0xe969, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData phone =
      IconData(0xe96a, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData phoneandorid =
      IconData(0xe96b, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData phoneandoridh =
      IconData(0xe96c, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData phoneholding =
      IconData(0xe96d, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData phoneholdingdouble =
      IconData(0xe96e, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData piggybank =
      IconData(0xe96f, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData pin =
      IconData(0xe970, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData pinch =
      IconData(0xe971, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData play =
      IconData(0xe972, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData playalt =
      IconData(0xe973, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData plug =
      IconData(0xe974, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData plus =
      IconData(0xe975, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData pluscircle =
      IconData(0xe976, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData plussquare =
      IconData(0xe977, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData point =
      IconData(0xe978, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData poundsign =
      IconData(0xe979, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData press =
      IconData(0xe97a, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData previous =
      IconData(0xe97b, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData previousalt =
      IconData(0xe97c, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData pricetag =
      IconData(0xe97d, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData printer =
      IconData(0xe97e, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData prioritizedown =
      IconData(0xe97f, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData prioritizeup =
      IconData(0xe980, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData prototype =
      IconData(0xe981, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData prototypemobile =
      IconData(0xe982, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData qrcode =
      IconData(0xe983, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData qrcodescan =
      IconData(0xe984, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData rain =
      IconData(0xe985, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData rainday =
      IconData(0xe986, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData rainnight =
      IconData(0xe987, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData receipt =
      IconData(0xe988, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData redo =
      IconData(0xe989, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData refreshdouble =
      IconData(0xe98a, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData refreshleft =
      IconData(0xe98b, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData refreshright =
      IconData(0xe98c, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData repository =
      IconData(0xe98d, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData resize =
      IconData(0xe98e, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData resizealt =
      IconData(0xe98f, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData responsive =
      IconData(0xe990, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData restart =
      IconData(0xe991, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData rightbar =
      IconData(0xe992, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData rotateaxisx =
      IconData(0xe993, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData rotateaxisxy =
      IconData(0xe994, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData rotateaxisy =
      IconData(0xe995, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData rotateleft =
      IconData(0xe996, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData rotateright =
      IconData(0xe997, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData rotateshape =
      IconData(0xe998, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData rubelsign =
      IconData(0xe999, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData rulercombined =
      IconData(0xe99a, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData rulerh =
      IconData(0xe99b, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData rulerv =
      IconData(0xe99c, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData rupeesign =
      IconData(0xe99d, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData sad =
      IconData(0xe99e, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData salebadge =
      IconData(0xe99f, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData scale =
      IconData(0xe9a0, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData scaledown =
      IconData(0xe9a1, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData scaleup =
      IconData(0xe9a2, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData screenflow =
      IconData(0xe9a3, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData script =
      IconData(0xe9a4, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData scrolldown =
      IconData(0xe9a5, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData scrolldowntwo =
      IconData(0xe9a6, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData scrollh =
      IconData(0xe9a7, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData scrollhtwo =
      IconData(0xe9a8, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData scrollup =
      IconData(0xe9a9, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData scrolluptwo =
      IconData(0xe9aa, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData scrollv =
      IconData(0xe9ab, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData scrollvtwo =
      IconData(0xe9ac, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData search =
      IconData(0xe9ad, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData select =
      IconData(0xe9ae, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData selectcursor =
      IconData(0xe9af, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData send =
      IconData(0xe9b0, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData serverstack =
      IconData(0xe9b1, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData shaka =
      IconData(0xe9b2, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData shapecircle =
      IconData(0xe9b3, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData shapecone =
      IconData(0xe9b4, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData shapecube =
      IconData(0xe9b5, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData shapecylinder =
      IconData(0xe9b6, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData shapeoctagonal =
      IconData(0xe9b7, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData shapepolygon =
      IconData(0xe9b8, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData shapesphere =
      IconData(0xe9b9, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData shapesquare =
      IconData(0xe9ba, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData share =
      IconData(0xe9bb, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData shoppingbag =
      IconData(0xe9bc, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData shoppingbagalt =
      IconData(0xe9bd, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData shoppingcart =
      IconData(0xe9be, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData shortcut =
      IconData(0xe9bf, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData shuffle =
      IconData(0xe9c0, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData sidebar =
      IconData(0xe9c1, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData signin =
      IconData(0xe9c2, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData signout =
      IconData(0xe9c3, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData slidercircleh =
      IconData(0xe9c4, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData slidercirclev =
      IconData(0xe9c5, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData sliderrectangleh =
      IconData(0xe9c6, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData sliderrectanglev =
      IconData(0xe9c7, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData smartglasses =
      IconData(0xe9c8, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData smarttv =
      IconData(0xe9c9, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData smartwatch =
      IconData(0xe9ca, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData smartwatchtime =
      IconData(0xe9cb, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData smile =
      IconData(0xe9cc, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData snow =
      IconData(0xe9cd, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData snowday =
      IconData(0xe9ce, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData snownight =
      IconData(0xe9cf, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData sortalphabeticdown =
      IconData(0xe9d0, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData sortalphabeticup =
      IconData(0xe9d1, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData sortamountdown =
      IconData(0xe9d2, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData sortamountup =
      IconData(0xe9d3, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData sortnumericdown =
      IconData(0xe9d4, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData sortnumericup =
      IconData(0xe9d5, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData splith =
      IconData(0xe9d6, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData splitv =
      IconData(0xe9d7, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData spread =
      IconData(0xe9d8, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData square =
      IconData(0xe9d9, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData stamp =
      IconData(0xe9da, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData standup =
      IconData(0xe9db, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData sticker =
      IconData(0xe9dc, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData stickynotes =
      IconData(0xe9dd, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData stickynotes2 =
      IconData(0xe9de, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData store =
      IconData(0xe9df, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData storm =
      IconData(0xe9e0, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData stormday =
      IconData(0xe9e1, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData stormnight =
      IconData(0xe9e2, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData substractback =
      IconData(0xe9e3, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData substractfront =
      IconData(0xe9e4, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData sun =
      IconData(0xe9e5, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData table =
      IconData(0xe9e6, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData tablet =
      IconData(0xe9e7, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData tableth =
      IconData(0xe9e8, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData tap =
      IconData(0xe9e9, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData taptwo =
      IconData(0xe9ea, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData task =
      IconData(0xe9eb, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData temperature =
      IconData(0xe9ec, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData terminal =
      IconData(0xe9ed, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData text =
      IconData(0xe9ee, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData textaligncenter =
      IconData(0xe9ef, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData textalignjustify =
      IconData(0xe9f0, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData textalignleft =
      IconData(0xe9f1, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData textalignright =
      IconData(0xe9f2, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData textcursor =
      IconData(0xe9f3, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData textdecoration =
      IconData(0xe9f4, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData textfield =
      IconData(0xe9f5, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData threeh =
      IconData(0xe9f6, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData threev =
      IconData(0xe9f7, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData thumbsdown =
      IconData(0xe9f8, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData thumbsup =
      IconData(0xe9f9, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData tobottom =
      IconData(0xe9fa, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData toggleswitch =
      IconData(0xe9fb, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData toleft =
      IconData(0xe9fc, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData topbar =
      IconData(0xe9fd, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData toright =
      IconData(0xe9fe, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData totop =
      IconData(0xe9ff, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData transformleft =
      IconData(0xea00, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData transformright =
      IconData(0xea01, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData trash =
      IconData(0xea02, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData tray =
      IconData(0xea03, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData traydelete =
      IconData(0xea04, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData trayempty =
      IconData(0xea05, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData trayexport =
      IconData(0xea06, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData trayimport =
      IconData(0xea07, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData trayminus =
      IconData(0xea08, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData trayplus =
      IconData(0xea09, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData traystack =
      IconData(0xea0a, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData twodrag =
      IconData(0xea0b, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData underline =
      IconData(0xea0c, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData undo =
      IconData(0xea0d, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData unite =
      IconData(0xea0e, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData unlink =
      IconData(0xea0f, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData upload =
      IconData(0xea10, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData usability =
      IconData(0xea11, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData user =
      IconData(0xea12, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData usercircle =
      IconData(0xea13, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData userdelete =
      IconData(0xea14, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData userflow =
      IconData(0xea15, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData userfollow =
      IconData(0xea16, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData userinterview =
      IconData(0xea17, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData userjourney =
      IconData(0xea18, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData userminus =
      IconData(0xea19, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData userplus =
      IconData(0xea1a, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData users =
      IconData(0xea1b, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData video =
      IconData(0xea1c, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData videoalt =
      IconData(0xea1d, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData videocamera =
      IconData(0xea1e, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData virtualreality =
      IconData(0xea1f, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData voiceassistant =
      IconData(0xea20, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData volumelow =
      IconData(0xea21, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData volumemax =
      IconData(0xea22, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData volumemid =
      IconData(0xea23, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData volumemin =
      IconData(0xea24, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData wallet =
      IconData(0xea25, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData web =
      IconData(0xea26, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData wideangle =
      IconData(0xea27, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData width =
      IconData(0xea28, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData wind =
      IconData(0xea29, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData windalt =
      IconData(0xea2a, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData windcloudy =
      IconData(0xea2b, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData windcloudyday =
      IconData(0xea2c, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData windcloudynight =
      IconData(0xea2d, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData window =
      IconData(0xea2e, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData windowdelete =
      IconData(0xea2f, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData windowminus =
      IconData(0xea30, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData windowplus =
      IconData(0xea31, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData windows =
      IconData(0xea32, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData wonsign =
      IconData(0xea33, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData wrapimgleft =
      IconData(0xea34, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData wrapimgright =
      IconData(0xea35, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData wrapleft =
      IconData(0xea36, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData wrapright =
      IconData(0xea37, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData yensign =
      IconData(0xea38, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData bookfill =
      IconData(0xea39, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData cartfill =
      IconData(0xea3a, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData checkfill =
      IconData(0xea3b, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData circlefill =
      IconData(0xea3c, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData fb =
      IconData(0xea3d, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData heartfill =
      IconData(0xea3e, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData plusfill =
      IconData(0xea3f, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData salefill =
      IconData(0xea40, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData twfill =
      IconData(0xea41, fontFamily: kFontFam, fontPackage: kFontPkg);
  static const IconData userfill =
      IconData(0xea42, fontFamily: kFontFam, fontPackage: kFontPkg);
}
